# Generated by Django 4.2 on 2023-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=models.EmailField(max_length=254, unique=True),
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
