# Generated by Django 4.2 on 2023-06-06 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_api", "0003_conversation_alter_user_username_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(("groups__isnull", True)),
                related_name="conversation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
